### ISSUE TITLE
на 12 подыхает бп

### ISSUE THREAD

**Issue by noctuum** [lagunaspb/TechMaintainance#131]
всю ночь дребезжал, думал кулер проца задевает провода
разобрал - оказалось кулер бп останавливается с таким звуком потом снова запускается

долго не проживет

**Comment by AlexeyKozulin** [comment]
Ну так туда кулер надо новый, а не весь БП

**Comment by AlexeyKozulin** [comment]
Ну а на самом деле, достаточно было смазать кулеры машинным маслом.
