### ISSUE TITLE
Установить Generals Zero Hour на компьютеры 5-13

### ISSUE THREAD

**Issue by AlexeyKozulin** [lagunaspb/TechMaintainance#34]
Есть пара любителей поиграть...

**Comment by Flagin** [comment]
3,5,6,7,8  установлено

**Comment by AlexeyKozulin** [comment]
На 5-ом по ярлыку не запустилось, попросил права администратора.

**Comment by AlexeyKozulin** [comment]
Ага, это генералы не запустились, а проект раптор просто выдает крит.ошибку при запуске. Класс. Вот какого хрена я должен после установки игр проверять, работают ли они?

**Comment by Flagin** [comment]
9
